### ISSUE TITLE
SwatchJS Website

### ISSUE THREAD

**Issue by Furchin** [builtforme/swatchjs#33]
Would be lovely to create a GitHub pages website for SwatchJS.

**Comment by joshessman** [comment]
I'd be happy to give it a shot.  I'll start working on it sometime this weekend probably

**Comment by Furchin** [comment]
If you get one up we'll find a proper domain for it! :)

**Comment by joshessman** [comment]
Great!  I've got something running [here](https://joshessman.github.io/swatchjs/) that you're welcome to take a look at.

**Comment by Furchin** [comment]
Looks like a solid start! If you want to submit a PR putting that in the not-yet-created `/docs` folder I'll configure GitHub pages to host it from there:

![screenshot 2017-09-30 09 52 09](https://user-images.githubusercontent.com/1891931/31047753-22f1ef0c-a5c5-11e7-972b-34641bf110f9.png)

**Comment by actuallyjamez** [comment]
Had a quick mess around and made [this](https://actuallyjamez.github.io/swatchjs/). Obviously, if you already have a site then no worries.

**Comment by Furchin** [comment]
@actuallyjamez I just merged #35 which adds a GitHub pages folder. I like your design, and if you'd want to submit a PR with your design that merges the existing content I'd be happy to have a look!

**Comment by actuallyjamez** [comment]
Ok thanks! I'll work on it and get back to you.

**Comment by Furchin** [comment]
Fixed in #36
